services:
  db:
    image: postgres:16.4-alpine3.20
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - data:/var/lib/postgresql/data
      - ./packages/docker/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment: 
      POSTGRES_PASSWORD: warehousepassword
      POSTGRES_USER: warehouseuser
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  otel:
    image: grafana/otel-lgtm
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
      - 30000:3000 # port 3000 is used already by the web app
volumes:
  data:
